# Generated by Django 3.2.5 on 2021-07-18 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(max_length=255)),
                ('last_name', models.TextField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('address', models.TextField(max_length=255)),
                ('city', models.TextField(max_length=50)),
                ('state', models.TextField(max_length=50)),
                ('zip', models.TextField(max_length=5)),
            ],
        ),
    ]
